### ISSUE TITLE
Investigate novel pub/sub failure

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1062]
In https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/75334450, the merge build for #1060, we got an (flaky) error we have yet to see:

```python
======================================================================
ERROR: test_message_pull_mode_e2e (pubsub.TestPubsub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/pubsub.py", line 123, in test_message_pull_mode_e2e
    subscription.acknowledge(ack_ids)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/pubsub/subscription.py", line 230, in acknowledge
    method='POST', path='%s:acknowledge' % (self.path,), data=data)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/connection.py", line 419, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.BadRequest: 400 You have not specified an ack ID in the request. (POST https://pubsub.googleapis.com/v1/projects/precise-truck-742/subscriptions/subscribing-now:acknowledge)
```

**Comment by dhermes** [comment]
Closing since #1085 also has issue
