### ISSUE TITLE
BigQuery System Tests Failing in Python3

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1071]
Seen on Travis and duplicated locally for me:

```python
======================================================================
ERROR: test_load_table_from_storage_then_dump_table (bigquery.TestBigQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/gcloud-python/system_tests/bigquery.py", line 270, in test_load_table_from_storage_then_dump_table
    writer.writerow(('Full Name', 'Age'))
TypeError: 'str' does not support the buffer interface

======================================================================
ERROR: test_load_table_from_storage_then_dump_table (bigquery.TestBigQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/gcloud-python/system_tests/bigquery.py", line 36, in tearDown
    doomed.delete()
  File "/path/to/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/storage/blob.py", line 243, in delete
    return self.bucket.delete_blob(self.name, client=client)
  File "/path/to/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/storage/bucket.py", line 399, in delete_blob
    _target_object=None)
  File "/path/to/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/connection.py", line 419, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.NotFound: 404 Not Found (DELETE https://www.googleapis.com/storage/v1/b/bq_load_test_1439925277970/o/person_ages.csv)

----------------------------------------------------------------------
Ran 11 tests in 46.300s

FAILED (errors=2)
```

**Comment by dhermes** [comment]
Also worth noting that this leaves a bucket undeleted / cleaned up after:

![screen_shot_027](https://cloud.githubusercontent.com/assets/520669/9340178/2675337a-45a3-11e5-9fb4-65a3633013d3.png)

**Comment by tseaver** [comment]
I will tackle this one ASAP.
