### ISSUE TITLE
Problem with protorpc version

### ISSUE THREAD

**Issue by Solyony** [GoogleCloudPlatform/gcloud-python#1133]
When I install gcloud to new environment it downloads the latest version of protorpc, which is 0.11.0
But this version has some changes, which cause error:

```
>>> from gcloud import storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Solyony/.virtualenvs/tests/lib/python2.7/site-packages/gcloud/storage/__init__.py", line 43, in <module>
    from gcloud.storage.blob import Blob
  File "/Users/Solyony/.virtualenvs/tests/lib/python2.7/site-packages/gcloud/storage/blob.py", line 28, in <module>
    from apitools.base.py import http_wrapper
  File "/Users/Solyony/.virtualenvs/tests/lib/python2.7/site-packages/apitools/base/py/__init__.py", line 10, in <module>
    from apitools.base.py.extra_types import *
  File "/Users/Solyony/.virtualenvs/tests/lib/python2.7/site-packages/apitools/base/py/extra_types.py", line 38, in <module>
    class DateField(messages.Field):
  File "/Users/Solyony/.virtualenvs/tests/lib/python2.7/site-packages/apitools/base/py/extra_types.py", line 50, in DateField
    class __metaclass__(messages.Field.__metaclass__):
AttributeError: type object 'Field' has no attribute '__metaclass__'
```

pip freeze:
```
gcloud==0.7.1
google-apitools==0.4.11
httplib2==0.9.1
oauth2client==1.5.0
protobuf==3.0.0a1
protorpc==0.11.0
pyasn1==0.1.8
pyasn1-modules==0.0.7
pycrypto==2.6.1
rsa==3.2
six==1.9.0
```

**Comment by dhermes** [comment]
Thanks for filing @Solyony!
