### ISSUE TITLE
gcloud.datastore causes "Invalid Credentials" error on GCE instance

### ISSUE THREAD

**Issue by miyakawataku** [GoogleCloudPlatform/gcloud-python#1201]
gcloud.datastore raises "Invalid Credentials" error when running on a GCE instance with proper service account scopes.

Program:

```python
# ds.py
from gcloud import datastore
client = datastore.Client()
entity = datastore.Entity(key=client.key('EntityKind'))
entity.update({
    'foo': u'bar',
    'baz': 1337,
    'qux': False,
})
client.put(entity)
```

Command line and output:

```
$ python ds.py 
Traceback (most recent call last):
  File "ds.py", line 10, in <module>
    client.put(entity)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/datastore/client.py", line 331, in put
    self.put_multi(entities=[entity])
  File "/usr/local/lib/python2.7/dist-packages/gcloud/datastore/client.py", line 357, in put_multi
    current.commit()
  File "/usr/local/lib/python2.7/dist-packages/gcloud/datastore/batch.py", line 203, in commit
    self.dataset_id, self.mutation, self._id)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/datastore/connection.py", line 329, in commit
    datastore_pb.CommitResponse)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/datastore/connection.py", line 113, in _rpc
    data=request_pb.SerializeToString())
  File "/usr/local/lib/python2.7/dist-packages/gcloud/datastore/connection.py", line 90, in _request
    raise make_exception(headers, content, use_json=False)
gcloud.exceptions.Unauthorized: 401 Invalid Credentials
```

Environment:

- Ubuntu 14.04
- Python 2.7.6
- gcloud 0.8.0

**Comment by miyakawataku** [comment]
Sorry it has turned out to be an issue of the service account scope.

The above error was reported when the GCE instance is allowed "API access to all Google Cloud services in the same project" on the Developers Console.

After I enabled "Datastore" access explicitly, the script came to work.
