### ISSUE TITLE
DNS doesn't parse creationTime field

### ISSUE THREAD

**Issue by kvdb** [GoogleCloudPlatform/gcloud-python#1362]
I know DNS is not oficially supported yet, but I'm reporting it anyway. I'm using the master `gcloud-python` repo with this code:

```python
client = dns.Client.from_service_account_json(                              
    'service-account.json', project='xyz-eu')           
zones = client.list_zones()                 
```
This is the error I get: 

```python
Traceback (most recent call last):
  ..
    zones = client.list_zones()
  File "/app/src/gcloud/gcloud/dns/client.py", line 94, in list_zones
    for resource in resp['managedZones']]
  File "/app/src/gcloud/gcloud/dns/zone.py", line 67, in from_api_repr
    zone._set_properties(resource)
  File "/app/src/gcloud/gcloud/dns/zone.py", line 218, in _set_properties
    cleaned['creationTime'] = float(cleaned['creationTime'])
ValueError: invalid literal for float(): 2015-04-02T13:21:24.943Z
```

**Comment by dhermes** [comment]
Thanks for the report!

**Comment by dhermes** [comment]
Will be "easy" to do once #1336 is in.

**Comment by dhermes** [comment]
Verified from the docs: https://cloud.google.com/dns/api/v1/managedZones#resource

> `creationTime`: The time that this resource was created on the server. This is in RFC3339 text format. Output only.
