### ISSUE TITLE
oauthclient.OAuth2Credentials does not implement create_scoped or create_scoped_required

### ISSUE THREAD

**Issue by tuanvu216** [GoogleCloudPlatform/gcloud-python#1412]
Right now, the gcloud-python API only authorize through service account. Can we add the user authorization using client_secret.json file?

https://developers.google.com/identity/protocols/OAuth2WebServer

```python
from oauth2client import client
from oauth2client.file import Storage
from oauth2client import tools

FLOW = flow_from_clientsecrets('client_secret.json',
                               scope='https://www.googleapis.com/auth/bigquery')
storage = Storage('bigquery_credentials.dat')
credentials = storage.get()
if credentials is None or credentials.invalid:
    credentials = run(FLOW, storage)
http = httplib2.Http()
http = credentials.authorize(http)
```

**Comment by dhermes** [comment]
You can use any [explicit credentials][1] you like, just pass them manually to the constructor

```python
from gcloud.service_foo import Client
credentials = run(FLOW, storage)
client = Client(credentials=credentials)
```

[1]: http://gcloud-python.readthedocs.org/en/latest/gcloud-auth.html#explicit-credentials

**Comment by dhermes** [comment]
@tuanvu216 Please re-open if this didn't answer your question

**Comment by tuanvu216** [comment]
Hi @dhermes,

This one works perfectly:

```python
from oauth2client.client import GoogleCredentials
from gcloud import bigquery

credentials = GoogleCredentials.get_application_default()
print credentials.to_json()

client = bigquery.Client(project='my-project-id',
                         credentials=credentials
                         )
```

However, I try this for the user authentication with client_secret.json, and bigquery_credentials.dat, but this one give me error:

```python
import httplib2
from apiclient.discovery import build
from apiclient.errors import HttpError
   
from oauth2client import client
from oauth2client.file import Storage
from oauth2client import tools

from gcloud import bigquery

BIGQUERY_SCOPE = 'https://www.googleapis.com/auth/bigquery'

FLOW = client.flow_from_clientsecrets('client_secret.json', scope=BIGQUERY_SCOPE)
storage = Storage('bigquery_credentials.dat')
flags = tools.argparser.parse_args(args=[])
credentials = storage.get()
if credentials is None or credentials.invalid:
    credentials = tools.run_flow(FLOW, storage, flags)
http = httplib2.Http()
http = credentials.authorize(http)
# print credentials.to_json()
# print http.to_json()
client = bigquery.Client(project='my-project-id',
                         credentials=credentials
                         )
```

Error message:
````
Traceback (most recent call last):
  File "gcloud_test.py", line 36, in <module>
    credentials=credentials
  File "/usr/local/lib/python2.7/dist-packages/gcloud/client.py", line 182, in __init__
    Client.__init__(self, credentials=credentials, http=http)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/client.py", line 127, in __init__
    credentials=credentials, http=http)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/connection.py", line 78, in __init__
    credentials, self.SCOPE)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/connection.py", line 118, in _create_scoped_credentials
    if credentials and credentials.create_scoped_required():
AttributeError: 'OAuth2Credentials' object has no attribute 'create_scoped_required'
```

How can I tune this to make the gcloud/connection.py works?

Thanks,
Tuan

**Comment by dhermes** [comment]
Ahh that is indeed an issue! Thanks for bringing it to our attention.

For now, a simple hack: convert your `OAuth2Credentials` object into a `GoogleCredentials` object

```python
credentials = tools.run_flow(FLOW, storage, flags)
# This is an instance of OAuth2Credentials
from oauth2client.client import GoogleCredentials
new_creds = GoogleCredentials(
    credentials.access_token,
    credentials.client_id,
    credentials.client_secret,
    credentials.refresh_token,
    credentials.token_expiry,
    credentials.token_uri,
    credentials.user_agent,
    revoke_uri=credentials.revoke_uri,
)
```

**Comment by dhermes** [comment]
@tseaver I think we should change [our current use][1] of `create_scoped` from

```python
if credentials and credentials.create_scoped_required():
    credentials = credentials.create_scoped(scope)
```

to

```python
if credentials
    try:
        if credentials.create_scoped_required():
            credentials = credentials.create_scoped(scope)
    except AttributeError:
        pass
```


[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/896044579b5dfaddb75e8c7cbf72b614b0d04c5e/gcloud/connection.py#L118-L119

**Comment by tseaver** [comment]
@dhermes Do we know that `OAuth2Credentials` objects will work otherwise?

**Comment by dhermes** [comment]
"Know" might be strong but AFAIK the only other things we use a credential for are getting access tokens for signing requests and providing a way to generate a signed URL (and neither `GoogleCredentials` nor `OAuth2Credentials` can do this since they don't have a key to sign with).
