### ISSUE TITLE
Pubsub.list_topics fails when there are no topics

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1439]
[Offending line][1]. Reproduce via:

```python
client = pubsub.Client()
>>> client.list_topics()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gcloud/pubsub/client.py", line 80, in list_topics
    for resource in resp['topics']]
KeyError: 'topics'
```

@tseaver ISTM we should locate all instances where we assume a key is present and just protect against this. The time between releases behooves us to be "protective" of users. (I realize that we've usually done it this way based on documented outputs.)

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/0910f9979a45af8cc2826dd4c6ff38d9efa5ccec/gcloud/pubsub/client.py#L80

**Comment by dhermes** [comment]
Found while reproducing #1438
