### ISSUE TITLE
Does this run in the standard google app engine runtime

### ISSUE THREAD

**Issue by danielecook** [GoogleCloudPlatform/gcloud-python#1522]
I am unable to get gcloud datastore to connect using the standard google app engine runtime.

**Comment by dhermes** [comment]
Yes this runs in App Engine. Can you provide some more details? What did you try? Do you have a stacktrace.

**Comment by danielecook** [comment]
I've almost gotten it to work... It took quite a bit of messing around with things. I'm not a huge fan of the `ndb` library as I want to be able to access the datastore from outside of appengine...there doesn't seem to be an easy solution there.

Here is the sticking point right now:

```
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/request_handler.py", line 226, in handle_interactive_request
    exec(compiled_code, self._command_globals)
  File "<string>", line 6, in <module>
  File "/Users/danielcook/Documents/git/cegwas-web/lib/gcloud/datastore/__init__.py", line 55, in <module>
    from gcloud.datastore.client import Client
  File "/Users/danielcook/Documents/git/cegwas-web/lib/gcloud/datastore/client.py", line 21, in <module>
    from gcloud.client import Client as _BaseClient
  File "/Users/danielcook/Documents/git/cegwas-web/lib/gcloud/client.py", line 21, in <module>
    from gcloud.credentials import get_credentials
  File "/Users/danielcook/Documents/git/cegwas-web/lib/gcloud/credentials.py", line 32, in <module>
    from oauth2client.service_account import ServiceAccountCredentials
ImportError: cannot import name ServiceAccountCredentials
```

I wasn't able to pass service account credentials despite defining environmental variables in `app.yaml`. Apparently, only certain environmental variables can be defined (why?). This is more an issue just in terms of testing locally though given that appengine has is provided service credentials in production.

I have used `gcloud auth login`... but appengine isn't looking for those.

**Comment by dhermes** [comment]
It seems you have an out-of-date version of `oauth2client`. Try updating.

As for why your environment variables in `app.yaml` don't work, it's because you're in GAE so the default credentials will be the [App Engine ones][1]. If you want to use a service account with a JSON key, you should just directly use `Client.from_service_account_json('/path/to/keyfile.json')`

RE: "access the datastore from outside of appengine...there doesn't seem to be an easy solution there." That's what the Cloud Datastore API is for (and this library).

[1]: http://gcloud-python.readthedocs.org/en/latest/gcloud-auth.html#google-app-engine-environment
[2]: http://gcloud-python.readthedocs.org/en/latest/gcloud-auth.html#service-accounts

**Comment by danielecook** [comment]
Ah - awesome. That fixed everything!

**Comment by dhermes** [comment]
Good deal!
