### ISSUE TITLE
cannot import name timestamp_pb2 when running on local ubuntu machine

### ISSUE THREAD

**Issue by vsubramani** [GoogleCloudPlatform/gcloud-python#1620]
Importing gcloud barfs on my local machine. Here the system and version details and the error message.

This may be [similar](https://github.com/GoogleCloudPlatform/gcloud-python/issues/1436) to what others are seeing. I can't reopen this issue, hence creating a new one. 

Python Version: 2.7.6
Ubuntu Version: 14.04
gcloud Version: 0.11

```
Traceback (most recent call last):
  File "Sample.py", line 1, in <module>
    from gcloud import pubsub
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 181, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/__init__.py", line 26, in <module>
    from gcloud.pubsub.client import Client
  File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/client.py", line 18, in <module>
    from gcloud.client import JSONClient
  File "/usr/local/lib/python2.7/dist-packages/gcloud/client.py", line 20, in <module>
    from gcloud._helpers import _determine_default_project
  File "/usr/local/lib/python2.7/dist-packages/gcloud/_helpers.py", line 26, in <module>
    from google.protobuf import timestamp_pb2
ImportError: cannot import name timestamp_pb2
```

**Comment by jgeewax** [comment]
Related to https://github.com/GoogleCloudPlatform/gcloud-common/issues/48 ?

**Comment by vsubramani** [comment]
Yes, and https://github.com/GoogleCloudPlatform/gcloud-python/issues/1436.

**Comment by dhermes** [comment]
@jgeewax Nope. It's all been catalogued in #1436.

@vsubramani I re-opened that issue for you. Let's discuss over there.

In particular, weigh in on whether you've run `pip install` with `--upgrade` and also run the suggested commands to find the `google/protobuf` folder and list the files contained in it

**Comment by dhermes** [comment]
Ahh I see. The original report for #1436 started in `gcloud-common`
