### ISSUE TITLE
Generic GCloudError thrown by psqworker

### ISSUE THREAD

**Issue by dreid93** [GoogleCloudPlatform/gcloud-python#1672]
I am unsure if this is a problem with `gcloud-python` or with `psq` though I am receiving an error when attempting occasionally when running the `psqworker`. 

The error thrown : 

```
Traceback (most recent call last):
  File "/home/dawsonreid/.envs/fb_utm_sync/bin/psqworker", line 11, in <module>
    sys.exit(main())
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/psq/psqworker.py", line 92, in main
    worker.listen()
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/psq/worker.py", line 79, in listen
    super(MultiprocessWorker, self).listen()
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/psq/worker.py", line 38, in listen
    block=True)
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/psq/queue.py", line 94, in dequeue
    return_immediately=not block, max_messages=max)
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/gcloud/pubsub/subscription.py", line 210, in pull
    method='POST', path='%s:pull' % (self.path,), data=data)
  File "/home/dawsonreid/.envs/fb_utm_sync/local/lib/python2.7/site-packages/gcloud/connection.py", line 343, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.GCloudError
```

psqworker will run properly for sometime before erroring out.

**Comment by tseaver** [comment]
`gcloud.exceptions.make_exception` only raises a `GCloudError` if it cannot decode a more specific error type using the response status code.  There should be some information about the reason for the API request failure in the `message` passed into the `GCloudError`.

Note that there may be occasional, transient failures in making API requests.  At the moment, `gcloud-python` does not attempt to handle such errors for you: your application (`psq.worker`, in this case) needs to have a policy about how retries, etc. are done.

**Comment by dhermes** [comment]
I'm surprised the traceback doesn't contain more. The [error raised][1] has [two arguments][2]:

```python
error = GCloudError(message, errors)
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/4ccb7a10829075192f844479b315df612136e05c/gcloud/connection.py#L342
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/4ccb7a10829075192f844479b315df612136e05c/gcloud/exceptions.py#L205

**Comment by jonparrott** [comment]
> your application (psq.worker, in this case) needs to have a policy about how retries, etc. are done.

I wrote psq, so that falls on me. You're probably right that it's just a transient error, but it is rather interesting that there isn't any more details.

**Comment by dhermes** [comment]
@jonparrott You aren't very good at vacation. Thanks for chiming in!

@dreid93 Any chance there is a bit more in the error message? If not, care to use `pdb`, `ipdb` or `%debug` in IPython to step into the error?

**Comment by jonparrott** [comment]
@dhermes I leave tomorrow. :P

**Comment by dreid93** [comment]
@dhermes I will attempt to step into the error to recreate though I cannot consistently reproduce. I will be watching for the error today.

**Comment by jonparrott** [comment]
PSQ version 0.3.0 has been released which should fix this. Please report and further issues over there. Thank you! :)
