### ISSUE TITLE
The project 'precise-truck-742' is not in the requisite Stackdriver service tier.

### ISSUE THREAD

**Issue by rimey** [GoogleCloudPlatform/gcloud-python#1768]
The system test that creates and deletes a metric descriptor is failing as below. This is what would happen if Stackdriver had not been enabled for this GCP project, so that's probably what's wrong.

Could one of you with access to the `precise-truck-742` project please use the cloud console to enable Stackdriver Monitoring? (This is not about enabling the API.) Just go to "Monitoring" in the left nav, choose to create a new Stackdriver Account, and click through the remaining screens.

```
test_create_and_delete_metric_descriptor (monitoring.TestMonitoring) ... ERROR
test_fetch_metric_descriptor (monitoring.TestMonitoring) ... ok
test_fetch_resource_descriptor (monitoring.TestMonitoring) ... ok
test_list_metric_descriptors (monitoring.TestMonitoring) ... ok
test_list_metric_descriptors_filtered (monitoring.TestMonitoring) ... ok
test_list_resource_descriptors (monitoring.TestMonitoring) ... ok
test_query (monitoring.TestMonitoring) ... ok
======================================================================
ERROR: test_create_and_delete_metric_descriptor (monitoring.TestMonitoring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/monitoring.py", line 174, in test_create_and_delete_metric_descriptor
    descriptor.create()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/monitoring/metric.py", line 152, in create
    data=self._to_dict())
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests3/lib/python3.4/site-packages/gcloud/connection.py", line 343, in api_request
    error_info=method + ' ' + url)
gcloud.exceptions.BadRequest: 400 The project 'precise-truck-742' is not in the requisite Stackdriver service tier. (POST https://monitoring.googleapis.com/v3/projects/precise-truck-742/metricDescriptors/)
----------------------------------------------------------------------
Ran 7 tests in 11.414s
FAILED (errors=1)
```

**Comment by dhermes** [comment]
On it.

**Comment by dhermes** [comment]
Done. Please re-open if it continues to fail. Can you send the failing build so I can retry it?

**Comment by rimey** [comment]
It was build 3615 that failed.

**Comment by dhermes** [comment]
OK. Just restarted https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/127310753

**Comment by rimey** [comment]
Thanks! The test now passes. (Subsequent failures have been on other other modules.)
