### ISSUE TITLE
 path "mysink" did not match expected pattern

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/gcloud-python#1817]
Looks like the Sink resource name is not the fully qualified version. Docs agree: https://cloud.google.com/logging/docs/api/ref_v2beta1/rest/v2beta1/projects.sinks#resource-logsink. I don't see a good reason why it wouldn't be the full name. Once again, I will bug people but for now I think we should disable the validation.

```
 {u'filter': u'logName=projects/bill-stackdriver-experiment/logs/syslog AND severity>=ERROR', u'destination': u'storage.googleapis.com/bill-new-stackdriver', u'name': u'mysink', u'outputVersionFormat': u'V2'} 
Validating sink name mysink bill-stackdriver-experiment 
Traceback (most recent call last):
  File "export.py", line 102, in <module>
    main(args.project_id, args.destination_bucket)
  File "export.py", line 84, in main
    list_sinks(client)
  File "export.py", line 54, in list_sinks
    sinks = client.list_sinks()[0]
  File "/Users/waprin/.virtualenvs/docsamples10/lib/python2.7/site-packages/gcloud/logging/client.py", line 196, in list_sinks
    for resource in resp.get('sinks', ())]
  File "/Users/waprin/.virtualenvs/docsamples10/lib/python2.7/site-packages/gcloud/logging/sink.py", line 112, in from_api_repr
    sink_name = _sink_name_from_path(resource['name'], client.project)
  File "/Users/waprin/.virtualenvs/docsamples10/lib/python2.7/site-packages/gcloud/logging/sink.py", line 45, in _sink_name_from_path
    return _name_from_project_path(path, project, _SINK_TEMPLATE)
  File "/Users/waprin/.virtualenvs/docsamples10/lib/python2.7/site-packages/gcloud/_helpers.py", line 458, in _name_from_project_path
    path, template.pattern,))
ValueError: path "mysink" did not match expected pattern "
    projects/            # static prefix
    (?P<project>[^/]+)   # initial letter, wordchars + hyphen
    /sinks/              # static midfix
    (?P<name>[^/]+)      # initial letter, wordchars + allowed punc
```

**Comment by dhermes** [comment]
Same idea as #1808?

**Comment by waprin** [comment]
Yep, except it will never get fixed because they don't consider it important enough to change the API for.

**Comment by tseaver** [comment]
@waprin Thanks for the report! 61004b72 made a similar change for metrics:  we are missing the system test for `list_sinks` which would have surfaced this issue.

**Comment by tseaver** [comment]
This is different than #1808, because the `Sink` resource as documented doesn't have the fully-qualified path in `name`.  I already made a similar change (61004b72) for `Metric.from_api_repr`, and added a system test for `Client.lists_metrics` which exercised it against real server-generated data.  #1825 makes the parallel change for sinks.
