### ISSUE TITLE
Mismatch between WriteLogEntriesRequest'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1889]

**Comment by tseaver** [comment]
@bjwatson, @tbetbetbe PTAL.  This is with `gax-google-login-v2` 0.7.9.

```python
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/logging/_gax.py", line 108, in write_entries
    labels, partial_success, options)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/logging/v2/logging_service_v2_api.py", line 281, in write_log_entries
    partial_success=partial_success)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 496, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 560, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message WriteLogEntriesRequest has no "partial_success" field.
```

**Comment by bjwatson** [comment]
@tseaver Do you have a recipe for reproducing this? Can I assume it's something like the recipe in https://github.com/GoogleCloudPlatform/gcloud-python/issues/1869?

**Comment by tseaver** [comment]
@bjwatson I think this would do it.

```bash
$ git clone git@github.com:GoogleCloudPlatform/gcloud
$ cd gcloud
$ tox -e system-tests --notest
$ .tox/system-tests/bin/python
```

and then:

```python
from google.logging.v2.config_service_v2_api import ConfigServiceV2Api
from google.logging.v2.logging_service_v2_api import LoggingServiceV2Api
from google.logging.v2.metrics_service_v2_api import MetricsServiceV2Api
from gcloud.logging._gax import _LoggingAPI
from gcloud.logging import Client

client = Client()
client._logging_api = _LoggingAPI(LoggingServiceV2Api())
logger = client.logger('gcloud-issue-1889')
logger.log_text('This will explode')
```

**Comment by tseaver** [comment]
Maybe one file is generated from an older version of its `.proto`?

**Comment by bjwatson** [comment]
Where is `.tox/system-tests/lib/python2.7/site-packages/google/logging/v2/logging_pb2.py` coming from? It does not match `google/logging/v2/logging_pb2.py` in [`grpc-google-logging-v2-0.7.8`](https://pypi.python.org/pypi/grpc-google-logging-v2/0.7.8) or [`grpc-google-logging-v2-0.7.10`](https://pypi.python.org/pypi/grpc-google-logging-v2/0.7.10).

**Comment by tseaver** [comment]
@bjwatson From `grpc-google-logging-v2-1.0.19`::

```bash
$ grep logging_pb2 .tox/py27/lib/python2.7/site-packages/grpc_google_logging_v2-1.0.19.dist-info/RECORD 
google/logging/v2/logging_pb2.py,sha256=qR-LZLvfOTZI_GHyRJmeR9jzpKbDfjjBYvN_M3R1SIw,24755
google/logging/v2/logging_pb2.pyc,,
```

**Comment by bjwatson** [comment]
I see. We have a stale logging 1.x release somewhere in the search path. I'll hunt it down and destroy it. :)

**Comment by bjwatson** [comment]
@tseaver There were stale versions of `grpc-google-logging-v2` on PyPi. I had looked for previous releases of `gax-google-logging-v2` and didn't find any, but I should have checked for the `grpc` version, too.

Looks like we're on to the next bug, and this issue can be closed:

```
brianwatson@brianwatson0:~/src/gapi-dev/gcloud-python$ .tox/system-tests/bin/pythonPython 2.7.11 (default, Apr 12 2016, 12:58:26) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.logging.v2.config_service_v2_api import ConfigServiceV2Api
>>> from google.logging.v2.logging_service_v2_api import LoggingServiceV2Api
>>> from google.logging.v2.metrics_service_v2_api import MetricsServiceV2Api
>>> from gcloud.logging._gax import _LoggingAPI
>>> from gcloud.logging import Client
>>> 
>>> client = Client()
>>> client._logging_api = _LoggingAPI(LoggingServiceV2Api())
>>> logger = client.logger('gcloud-issue-1889')
>>> logger.log_text('This will explode')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/brianwatson/src/gapi-dev/gcloud-python/gcloud/logging/logger.py", line 186, in log_text
    client.logging_api.write_entries([entry_resource])
  File "/usr/local/google/home/brianwatson/src/gapi-dev/gcloud-python/gcloud/logging/_gax.py", line 107, in write_entries
    labels, partial_success, options)
  File "/usr/local/google/home/brianwatson/src/gapi-dev/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/google/logging/v2/logging_service_v2_api.py", line 282, in write_log_entries
    self._write_log_entries(request, options)
  File "/usr/local/google/home/brianwatson/src/gapi-dev/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/google/gax/api_callable.py", line 474, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/google/home/brianwatson/src/gapi-dev/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/google/gax/api_callable.py", line 462, in base_caller
    return api_call(*args)
  File "/usr/local/google/home/brianwatson/src/gapi-dev/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/google/gax/api_callable.py", line 427, in inner
    sys.exc_info()[2])
google.gax.errors.GaxError: GaxError(RPC failed, caused by NetworkError(code=StatusCode.INVALID_ARGUMENT, details="A log name must be specified for each log entry"))
```

**Comment by tseaver** [comment]
I have just pushed a fix for that error on #1892.

**Comment by tseaver** [comment]
After setting up with [this gist](https://gist.github.com/tseaver/a28141aa9b1077fde80ed535744edc3c), `Logger.log_text()` works when the client is configured with a GAX adapter.

**Comment by bjwatson** [comment]
Awesome!
