### ISSUE TITLE
Mismatch between 'CreateSinkRequest' and 'ConfigServiceV2Api.create_sink'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1890]
@bjwatson, @tbetbetbe PTAL.  Reproduce via:

```bash
$ git clone git@github.com:GoogleCloudPlatform/gcloud
$ cd gcloud
$ tox -e system-tests --notest
$ .tox/system-tests/bin/python
```

and then:

```python
>>> from google.logging.v2.config_service_v2_api import ConfigServiceV2Api
>>> from gcloud.logging._gax import _SinksAPI
>>> from gcloud.logging import Client
>>> client = Client()
>>> client._sinks_api = _SinksAPI(ConfigServiceV2Api())
>>> sink = client.sink('gcloud-issue-1890-sink', 'logName=gcloud-issue-1890',
...                    'storage.googleapis.com/your-bucket-name')
>>> sink.exists()
False
>>> sink.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/logging/sink.py", line 117, in create
    self.project, self.name, self.filter_, self.destination)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/logging/_gax.py", line 188, in sink_create
    self._gax_api.create_sink(parent, sink_pb, options)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/logging/v2/config_service_v2_api.py", line 302, in create_sink
    sink=sink)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 496, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 560, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message CreateSinkRequest has no "parent" field.
```

**Comment by tseaver** [comment]
Seems quite similar to #1889.

**Comment by tseaver** [comment]
Similar to #1889, `logging_config_pb2.py` is coming from `grpc-google-logging-v2` 1.0.19:

```bash
$ grep logging_config_pb2 .tox/py27/lib/python2.7/site-packages/grpc_google_logging_v2-1.0.19.dist-info/RECORD 
google/logging/v2/logging_config_pb2.py,sha256=eREUL6GEoMiP1HboU6vVuSccHYD_KKHieiIaI_kGEZY,21014
google/logging/v2/logging_config_pb2.pyc,,
```

**Comment by tseaver** [comment]
Once I recreate the tox enviroment with the correct `grpc-google-logging-v2` version (0.7.10), `Sink.create()` over GAX (which calls `ConfigServiceV2Api.create_sink`) fails with an apparent conflict, even though `Sink.get()` over GAX (which calls `ConfigServiceV2Api.get_sink`) converts the `NOT_FOUND` exception to False:

```python
>>> s1.exists()  # JSON GET, maps 404 -> False
False
>>> s2.exists()  # GAX/gRPC `GetSink`, maps `NOT_FOUND` -> False
False
>>> s2.create()  # GAX/gRPC `CreateSink`
google.gax.errors.GaxError: GaxError(RPC failed, caused by NetworkError(code=StatusCode.ALREADY_EXISTS, details="Requested entity already exists"))
>>> s1.create()   # JSON `projects.sinks.create`, succeeds
>>> s1.exists()   # JSON `projects.sinks.get`, 200 -> True
True
>>> s2.exists()  # GAX/gRPC `GetSink`, success -> True
True
```

Use [this gist](https://gist.github.com/tseaver/a28141aa9b1077fde80ed535744edc3c) to reproduce.

**Comment by bjwatson** [comment]
@tseaver I believe I have fixed this with https://github.com/GoogleCloudPlatform/gcloud-python/pull/1904

BTW, it's not obvious that `cloud-logs@google.com` needs to be an owner for the project. It took me a couple hours to figure out how to get past the "Cloud Logging needs owner permissions on the bucket" error, including reading through:

* https://github.com/GoogleCloudPlatform/gcloud-python/issues/1614
* https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/584
* and finally finding the answer in https://github.com/GoogleCloudPlatform/gcloud-ruby/pull/585/files for Ruby

Could you add something to the `gcloud-python` docstring(s) (and other `gcloud-*` repos) to make this more clear? I will also ask the Logging team to add this to their proto documentation, so it's included in our gax layer docstrings.
