### ISSUE TITLE
Mismatch between 'CreateMetricRequest' and 'MetricsServiceV2Api.create_metric'

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1891]
@bjwatson, @tbetbetbe PTAL.  Needs to have #1888 merged here;  after that, reproduce via:

```bash
$ git clone git@github.com:GoogleCloudPlatform/gcloud
$ cd gcloud
$ tox -e system-tests --notest
$ .tox/system-tests/bin/python
```

and then:

```python
>>> from google.logging.v2.metrics_service_v2_api import MetricsServiceV2Api
>>> from gcloud.logging._gax import _MetricssAPI
>>> from gcloud.logging import Client
>>> client = Client()
>>> client._metrics_api = _MetricssAPI(MetricsServiceV2Api())
>>> metric = client.metric('gcloud-issue-xxxx-metric', 'logName=gcloud-issue-xxxx')
>>> metric.exists()
False
>>> metric.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/logging/metric.py", line 113, in create
    self.project, self.name, self.filter_, self.description)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/gcloud/logging/_gax.py", line 322, in metric_create
    self._gax_api.create_log_metric(parent, metric_pb, options)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/logging/v2/metrics_service_v2_api.py", line 302, in create_log_metric
    metric=metric)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 496, in init
    field = _GetFieldByName(message_descriptor, field_name)
  File "/home/tseaver/projects/agendaless/Google/src/gcloud-python/.tox/py27/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 560, in _GetFieldByName
    (message_descriptor.name, field_name))
ValueError: Protocol message CreateLogMetricRequest has no "parent" field.
```

Clearly similar to #1890.

**Comment by bjwatson** [comment]
Seems to also be fixed by https://github.com/GoogleCloudPlatform/gcloud-python/pull/1904

**Comment by tseaver** [comment]
Via #1904.
