### ISSUE TITLE
pip install error on mac

### ISSUE THREAD

**Issue by jihobak** [GoogleCloudPlatform/gcloud-python#1933]
I would like to check if this Is from my fault.
Thanks :)
 

```
 Collecting gcloud
  Using cached gcloud-0.16.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): httplib2>=0.9.1 in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from gcloud)
Collecting google-gax>=0.12.0 (from gcloud)
Requirement already satisfied (use --upgrade to upgrade): six in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from gcloud)
Requirement already satisfied (use --upgrade to upgrade): protobuf!=3.0.0.b2.post1,>=3.0.0b2 in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from gcloud)
Collecting gax-google-pubsub-v1 (from gcloud)
Collecting grpcio>=0.14.0 (from gcloud)
  Using cached grpcio-0.15.0.tar.gz
Collecting oauth2client>=2.0.1 (from gcloud)
Collecting googleapis-common-protos (from gcloud)
Requirement already satisfied (use --upgrade to upgrade): ply==3.8 in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from google-gax>=0.12.0->gcloud)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from protobuf!=3.0.0.b2.post1,>=3.0.0b2->gcloud)
Collecting grpc-google-pubsub-v1>=0.7.10 (from gax-google-pubsub-v1->gcloud)
Collecting enum34>=1.0.4 (from grpcio>=0.14.0->gcloud)
  Using cached enum34-1.1.6-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): futures>=2.2.0 in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from grpcio>=0.14.0->gcloud)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules>=0.0.5 in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from oauth2client>=2.0.1->gcloud)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages (from oauth2client>=2.0.1->gcloud)
Collecting rsa>=3.1.4 (from oauth2client>=2.0.1->gcloud)
  Using cached rsa-3.4.2-py2.py3-none-any.whl
Building wheels for collected packages: grpcio
  Running setup.py bdist_wheel for grpcio ... error
  Complete output from command /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/tmpaoy2j79vpip-wheel- --python-tag cp35:
  /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/setuptools/dist.py:316: UserWarning: Module enum was already imported from /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/enum.py, but /private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/.eggs/enum34-1.1.6-py3.5.egg is being added to sys.path
    pkg_resources.working_set.add(dist, replace=True)
  running bdist_wheel
  running build
  running build_py
  running build_proto_modules
  Traceback (most recent call last):
    File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/src/python/grpcio/commands.py", line 229, in run
      self.run_command('build_proto_modules')
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/src/python/grpcio/commands.py", line 159, in run
      raise CommandError('could not find protoc')
  commands.CommandError: could not find protoc

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/setup.py", line 258, in <module>
      test_runner=TEST_RUNNER,
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/src/python/grpcio/commands.py", line 231, in run
      sys.stderr.write('warning: %s\n' % error.message)
  AttributeError: 'CommandError' object has no attribute 'message'

  ----------------------------------------
  Failed building wheel for grpcio
  Running setup.py clean for grpcio
Failed to build grpcio
Installing collected packages: enum34, grpcio, rsa, oauth2client, google-gax, googleapis-common-protos, grpc-google-pubsub-v1, gax-google-pubsub-v1, gcloud
  Running setup.py install for grpcio ... error
    Complete output from command /Users/jihobak/.pyenv/versions/anaconda3-2.4.0/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-acbpix4d-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_proto_modules
    Traceback (most recent call last):
      File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/src/python/grpcio/commands.py", line 229, in run
        self.run_command('build_proto_modules')
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/src/python/grpcio/commands.py", line 159, in run
        raise CommandError('could not find protoc')
    commands.CommandError: could not find protoc

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/setup.py", line 258, in <module>
        test_runner=TEST_RUNNER,
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/src/python/grpcio/commands.py", line 231, in run
        sys.stderr.write('warning: %s\n' % error.message)
    AttributeError: 'CommandError' object has no attribute 'message'

    ----------------------------------------
Command "/Users/jihobak/.pyenv/versions/anaconda3-2.4.0/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-acbpix4d-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jm/bkqzc2ts4bs13wflp1dw158m0000gn/T/pip-build-sa02dhx6/grpcio/
```

**Comment by daspecster** [comment]
Hello @jihobak, this appears to be an issue directly with `grpcio` and somewhat related to #1928, #1858.
https://github.com/grpc/grpc/issues/7134 may also be related.

**Comment by tseaver** [comment]
@jihobak please give https://pypi.python.org/pypi/gcloud/0.16.1 a spin, and let us know if it resolves the issue for you.

**Comment by daspecster** [comment]
@jihobak, also this might be good to know/follow. https://github.com/grpc/grpc/issues/7135#issuecomment-229453868

**Comment by jihobak** [comment]
@daspecster @tseaver 
Thanks for you guys help 👍 
It's simple, The problem is six,
```
pip install --upgrade six
```
After upgrading six, I install gcloud successfully

**Comment by tseaver** [comment]
@jihobak Glad you found a fix!
