### ISSUE TITLE
Pub/Sub empty topic batch fails

### ISSUE THREAD

**Issue by tcroiset** [GoogleCloudPlatform/gcloud-python#1955]
```python
with topic.batch() as batch:
  for obj in rows:
    batch.publish(b'bla')
```
fails if rows is empty:

Traceback (most recent call last):
…
File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/topic.py", line 420, in __exit__
self.commit()
File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/topic.py", line 449, in commit
message_ids = api.topic_publish(self.topic.full_name, self.messages[:])
File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/connection.py", line 205, in topic_publish
method='POST', path='/%s:publish' % (topic_path,), data=data)
File "/usr/local/lib/python2.7/dist-packages/gcloud/connection.py", line 344, in api_request
error_info=method + ' ' + url)
BadRequest: 400 The value for message_count is too small. You passed 0 in the request, but the minimum value is 1. (POST https://pubsub.googleapis.com/v1/projects/karos-api/topics/api-prod:publish)

**Comment by tseaver** [comment]
Thanks for the report!  `gcloud.pubsub.topic.Batch.commit` should indeed be a no-op if there are no messages accumulated.
