### ISSUE TITLE
Weird errors with pyenv; File <string> key error

### ISSUE THREAD

**Issue by danielecook** [GoogleCloudPlatform/gcloud-python#2038]
Every time I invoke python I see a long list of google python modules reporting errors.

Error processing line 2 of /usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site-packages/gax_google_logging_v2-0.7.12-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site-packages/gax_google_pubsub_v1-0.7.12-py2.7-nspkg.pth:

```
  Traceback (most recent call last):
    File "/usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site-packages/googleapis_common_protos-1.2.0-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site-packages/grpc_google_logging_v2-0.7.12-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site-packages/grpc_google_pubsub_v1-0.7.12-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/var/pyenv/versions/2.7.11/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'
```

**Comment by daspecster** [comment]
Hello @danielecook!

There is a similar issue for another package on [stackoverflow](http://stackoverflow.com/questions/36757122/windows-7-pip-error-after-kivy-installation) and they suggest uninstalling and reinstalling.

Is this a fresh virtual environment that you've installed gcloud-python in?

**Comment by danielecook** [comment]
That fixed it. Thanks!

**Comment by daspecster** [comment]
Great to hear. Thanks for letting us know!

**Comment by richardpenman** [comment]
I got the same error message and needed to remove the following packages:

    pip uninstall google-cloud-bigquery google-cloud-core googleapis-common-protos

However reinstalling them produces the same error. Any idea what is going on?
OSX 10.11.6, Python 2.7.

**Comment by dhermes** [comment]
Have not experienced this. Can you provide some commands so we can try to reproduce?

**Comment by richardpenman** [comment]
Basically if I add any of these packages like this:

    pip install google-cloud-bigquery google-cloud-core googleapis-common-protos

Then when use Python command get the warning messages like above:
    
```
$ python
Error processing line 3 of /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google_cloud_bigquery-0.22.1-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 3 of /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google_cloud_core-0.22.1-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/googleapis_common_protos-1.5.0-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Python 2.7.11 (default, Dec 26 2015, 17:47:53)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by dhermes** [comment]
Got it. So it's the same error as reported. I think the issue may be with how you are uninstalling. `pip uninstall` may not actually pick up the offending `pth` files.

Have you tried in a brand new virtual environment?

**Comment by richardpenman** [comment]
Yes they work fine in a fresh virtualenv, or on my Linux server.

**Comment by dhermes** [comment]
So it's definitely an issue with the environment. Sorry your install got borked. I'm happy to help you `grep` around for the `pth` files.

**Comment by richardpenman** [comment]
Thanks, here are the contents of the offending pth files:

google_cloud_bigquery-0.22.1-py2.7-nspkg.pth:

```
import sys, types, os;pep420 = sys.version_info > (3, 3);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and not pep420 and sys.modules.setdefault('google', types.ModuleType('google'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;pep420 = sys.version_info > (3, 3);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and not pep420 and sys.modules.setdefault('google', types.ModuleType('google'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;pep420 = sys.version_info > (3, 3);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google', 'cloud'));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and not pep420 and sys.modules.setdefault('google.cloud', types.ModuleType('google.cloud'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['google'], 'cloud', m)
```

google_cloud_core-0.22.1-py2.7-nspkg.pth
```
import sys, types, os;pep420 = sys.version_info > (3, 3);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and not pep420 and sys.modules.setdefault('google', types.ModuleType('google'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;pep420 = sys.version_info > (3, 3);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and not pep420 and sys.modules.setdefault('google', types.ModuleType('google'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;pep420 = sys.version_info > (3, 3);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google', 'cloud'));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and not pep420 and sys.modules.setdefault('google.cloud', types.ModuleType('google.cloud'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['google'], 'cloud', m)
```

googleapis_common_protos-1.5.0-py2.7-nspkg.pth
```
import sys, types, os;p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and sys.modules.setdefault('google', types.ModuleType('google'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('google', 'logging'));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and sys.modules.setdefault('google.logging', types.ModuleType('google.logging'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['google'], 'logging', m)
```

Does anything look out of order there?

And here are the list of google API modules installed with pip:

```
google-auth (0.4.0)
google-auth-httplib2 (0.0.2)
google-cloud-bigquery (0.22.1)
google-cloud-core (0.22.1)
googleapis-common-protos (1.5.0)
```

**Comment by dhermes** [comment]
I'm not clear on what the error is, but you should just forcefully remove the `pth` files and reinstall. Hopefully this fixes the issue.

**Comment by richardpenman** [comment]
Those files are deleted when uninstall the modules and the above errors disappear, but reinstalling creates them again.

**Comment by dhermes** [comment]
Do you have some files in tthe `site-packages/google` directory that AREN'T namespace packages?

**Comment by richardpenman** [comment]
Here are the contents of that directory:

```
$ ls /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google
__init__.py   __init__.pyc  auth/         oauth2/       protobuf/
```

**Comment by treetoc** [comment]
Did anyone solve that issue?

**Comment by tseaver** [comment]
@treetoc the original poster [reported](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2038#issuecomment-236478301) that installing in a fresh virtual environment fixed the problem.
