### ISSUE TITLE
Happybase system test: setupModule failure

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#2076]
From: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/151011041#L710

```python
======================================================================
ERROR: setUpModule (bigtable_happybase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/bigtable_happybase.py", line 76, in setUpModule
    set_connection()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/bigtable_happybase.py", line 69, in set_connection
    operation = instance.create()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/bigtable/instance.py", line 362, in create
    request_pb, self._client.timeout_seconds)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 305, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 203, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
AbortionError: AbortionError(code=StatusCode.ALREADY_EXISTS, details="Transaction Failed : Transaction cannot complete : Instance projects/precise-truck-742/instances/gcloud-151011041-1470768319 already exists.")
----------------------------------------------------------------------
```

**Comment by dhermes** [comment]
That's a new one. Will look into it.

**Comment by tseaver** [comment]
I think we have fixes in play for all the other flaky errors:  it would be good to have a fix for this one, too.

**Comment by dhermes** [comment]
Sorry haven't had a chance yet. Will try to tackle this afternoon.
