### ISSUE TITLE
'test_topic_iam_policy':  Authentication backend unavailable

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#2170]
From: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/154249353#L828-L840

```python
======================================================================
ERROR: test_topic_iam_policy (pubsub.TestPubsub)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/system_tests/pubsub.py", line 219, in test_topic_iam_policy
    policy = topic.get_iam_policy()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/pubsub/topic.py", line 343, in get_iam_policy
    resp = api.get_iam_policy(self.full_name)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/pubsub/connection.py", line 496, in get_iam_policy
    return conn.api_request(method='GET', path=path)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/system-tests/lib/python2.7/site-packages/gcloud/connection.py", line 347, in api_request
    error_info=method + ' ' + url)
ServiceUnavailable: 503 Authentication backend unavailable. (GET https://pubsub.googleapis.com/v1/projects/precise-truck-742/topics/test-topic-iam-policy-topic-154249353-1471896177:getIamPolicy)
```

**Comment by dhermes** [comment]
BLERG!

**Comment by tseaver** [comment]
I'm going to put on my Pollyanna/Candide hat and claim that #2195 has resolved this issue.
