### ISSUE TITLE
Failing build due to order of url params?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#833]
Build: https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/58770268
Full log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/58770269/log.txt

Snippet that I think matters:

```
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/gcloud/storage/test_api.py", line 153, in test_non_use_default
    self._list_buckets_non_empty_helper('PROJECT', use_default=True)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/gcloud/storage/test_api.py", line 147, in _list_buckets_non_empty_helper
    self.assertEqual(http._called_with['uri'], URI)
AssertionError: 'https://www.googleapis.com/storage/v1/b?project=PROJECT&projection=noAcl' != 'https://www.googleapis.com/storage/v1/b?projection=noAcl&project=PROJECT'
- https://www.googleapis.com/storage/v1/b?project=PROJECT&projection=noAcl
?                                                ----------------
+ https://www.googleapis.com/storage/v1/b?projection=noAcl&project=PROJECT
```

Guessing we should parse the URL params and compare dictionaries instead of doing a string comparison?

**Comment by dhermes** [comment]
Yeah I noticed the failure yesterday. It's very strange we've never seen it happen, we thought we covered them all.
