### ISSUE TITLE
Intermittent storage regression failure

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#836]
https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/58811668

```
======================================================================
ERROR: setUpClass (storage.TestStoragePseudoHierarchy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/regression/storage.py", line 241, in setUpClass
    blob.delete()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/regression3/lib/python3.4/site-packages/gcloud/storage/blob.py", line 264, in delete
    return self.bucket.delete_blob(self.name)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/regression3/lib/python3.4/site-packages/gcloud/storage/bucket.py", line 361, in delete_blob
    self.connection.api_request(method='DELETE', path=blob_path)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/regression3/lib/python3.4/site-packages/gcloud/connection.py", line 293, in api_request
    raise make_exception(response, content)
gcloud.exceptions.NotFound: 404 Not Found
----------------------------------------------------------------------
```

**Comment by tseaver** [comment]
I restarted the build.

**Comment by dhermes** [comment]
I've been seeing these "eventual consistency" errors in 1 out of every 4 builds (not a scientific number). We should consider doing something about this.

I never deleted the retry code from #535 so we could put that back?

The `gcloud-node` folks have gone as far as building retries into the library to address regression test failures.

**Comment by dhermes** [comment]
Merging into #1100
