### ISSUE TITLE
Subscription.pull() fails with KeyError

### ISSUE THREAD

**Issue by campoy** [GoogleCloudPlatform/gcloud-python#899]
Hi,

My code below fails with a KeyError coming from the library:

```python
  sub = Subscription(SUBSCRIPTION_NAME, Topic(INCOMING_TOPIC_NAME))

  while True:
    try:
      msgs = sub.pull()
      ...
    except:
      msg = 'poll %s: %s' % (SUBSCRIPTION_NAME, traceback.format_exc())
      print msg
```

Fails with the message:

```
poll extractors: Traceback (most recent call last):
  File "main.py", line 46, in main
    msgs = sub.pull()
  File "/usr/local/lib/python2.7/dist-packages/gcloud/pubsub/subscription.py", line 176, in pull
    for info in response['receivedMessages']]
KeyError: 'receivedMessages'
```

This seems like a bug on the pubsub library code.

**Comment by dhermes** [comment]
Indeed it does! Thanks @campoy for filing.

I'm wondering how to reproduce a response without that key, but an easy "fix" (for us) is to just use

```python
response.get('receivedMessages', ())
```

**Comment by tseaver** [comment]
FWIW: this is the hardening I mentioned in #893.
