### ISSUE TITLE
Build failing due to Pylint issue with astroid?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#968]
Not sure what's up, but an import is failing somehow on https://travis-ci.org/GoogleCloudPlatform/gcloud-python/builds/69769611 ?

Traceback I'm seeing is:

```bash
Traceback (most recent call last):
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/bin/pylint", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/src/pylint/bin/pylint", line 3, in <module>
    run_pylint()
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/src/pylint/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/src/pylint/pylint/lint.py", line 1292, in __init__
    linter.load_plugin_modules(plugins)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/src/pylint/pylint/lint.py", line 498, in load_plugin_modules
    module = modutils.load_module_from_name(modname)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/lib/python2.7/site-packages/astroid/modutils.py", line 137, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/lib/python2.7/site-packages/astroid/modutils.py", line 180, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/src/pylint/pylint/extensions/check_docs.py", line 10, in <module>
    from pylint.checkers.utils import node_frame_class
  File "/home/travis/build/GoogleCloudPlatform/gcloud-python/.tox/lint/src/pylint/pylint/checkers/utils.py", line 27, in <module>
    from astroid import helpers
```

/cc @dhermes

**Comment by dhermes** [comment]
We are using the docstring checker that hasn't been released yet (they said it would be around July 15) so we are installing `pylint` [from head][1].

Before running `tox -e lint --recreate` I had

```bash
$ cd .tox/lint/src/pylint/
$ hg log -l 1
changeset:   2388:33e334be064c
tag:         tip
user:        Claudiu Popa <cpopa@cloudbasesolutions.com>
date:        Wed Jun 24 15:46:58 2015 +0300
summary:     Add tests for checking the ability to understand one-argument type builtin.
```

After recreating (pulling from head), I get the same failure you do and have

```bash
$ cd .tox/lint/src/pylint/
$ hg log -l 1
changeset:   2421:cb6aed4f60b1
tag:         tip
user:        Claudiu Popa <cpopa@cloudbasesolutions.com>
date:        Mon Jul 06 20:36:18 2015 +0300
summary:     Remove trailing whitespace.
```

We can pin somewhere before `2421:cb6aed4f60b1` until the next release to make sure it stays stable?

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/2ebc15a92ac77a6cf40fd6febe50f71001b6ec7c/tox.ini#L57
